// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL8vpQLQ7ndZTe4VkrV7PAEV0X27Almgk',
    appId: '1:123524740924:web:1f27803be1f667027c9039',
    messagingSenderId: '123524740924',
    projectId: 'domashka-c897e',
    authDomain: 'domashka-c897e.firebaseapp.com',
    storageBucket: 'domashka-c897e.firebasestorage.app',
    measurementId: 'G-VDSXXSL92N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBqMMzorzQAPazqTW599ZjBtZC5-ie0XU',
    appId: '1:123524740924:android:d72e1e1a73ac8f767c9039',
    messagingSenderId: '123524740924',
    projectId: 'domashka-c897e',
    storageBucket: 'domashka-c897e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL8vpQLQ7ndZTe4VkrV7PAEV0X27Almgk',
    appId: '1:123524740924:web:be64c764929710537c9039',
    messagingSenderId: '123524740924',
    projectId: 'domashka-c897e',
    authDomain: 'domashka-c897e.firebaseapp.com',
    storageBucket: 'domashka-c897e.firebasestorage.app',
    measurementId: 'G-HP4GCX135D',
  );
}
